print('Введите первый этап развития человека')
first_stage = input()
print('Введите второй этап развития человека')
second_stage = input()
print('Введите третий этап развития человека')
third_stage = input()
print('Введите четвертый этап развития человека')
fourth_stage = input()
print('Введите пятый этап развития человека')
fifth_stage = input()
print('Введите шестой этап развития человека')
sixth_stage = input()